name: Update README

on:
  schedule:
    - cron: '0 0 * * *'  # æ¯å¤© UTC 0 ç‚¹æ‰§è¡Œä¸€æ¬¡ï¼ˆåŒ—äº¬æ—¶é—´æ—©ä¸Š 8 ç‚¹ï¼‰
  workflow_dispatch:  # å…è®¸æ‰‹åŠ¨è§¦å‘

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Auto update README.md
        run: |
          echo "ðŸŒŸ This is an auto-update test! â° $(date)" > README.md
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add README.md
          git commit -m "Auto update README.md at $(date +'%Y-%m-%d %H:%M:%S')" || echo "No changes"
          git push
